image: archlinux
packages:
  - meson
  - wayland
  - wayland-protocols
  - cairo
  - libxkbcommon
  # needed for clang-format
  - clang
sources:
  - https://github.com/emerison/slurp
tasks:
  - setup: |
      cd slurp
      meson setup build
  - build: |
      cd slurp
      ninja -C build all clang-format-check
